// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWtcF0o9ZZeDBZpb8KM_-yrwk9a5iAP8g',
    appId: '1:390478988337:android:373470fcf76e08b73d4110',
    messagingSenderId: '390478988337',
    projectId: 'flutterfirebasefirst-8a2e7',
    storageBucket: 'flutterfirebasefirst-8a2e7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHcEcSptAXO1PCt0XNTQGbo0ZTjsFm8oA',
    appId: '1:390478988337:ios:1fb04a9f9a7bc4113d4110',
    messagingSenderId: '390478988337',
    projectId: 'flutterfirebasefirst-8a2e7',
    storageBucket: 'flutterfirebasefirst-8a2e7.appspot.com',
    iosClientId: '390478988337-8i1vh4k4ul0r0sl9j2stk3nv640p1bu4.apps.googleusercontent.com',
    iosBundleId: 'com.example.akxarApp',
  );
}
